# Generated by Django 4.0.5 on 2022-06-26 22:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_score_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_nickname', models.CharField(max_length=20)),
                ('text_comment', models.TextField()),
                ('movie_id', models.CharField(max_length=20)),
                ('movie_title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 6, 26, 22, 32, 51, 808657, tzinfo=utc))),
                ('comment_repeat', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 22, 32, 51, 808657, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ReplayComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_nickname', models.CharField(max_length=20)),
                ('text_replay_comment', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 6, 26, 22, 32, 51, 808657, tzinfo=utc))),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_result', models.BooleanField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_nickname', models.CharField(max_length=20)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.comment')),
            ],
        ),
    ]
