# Generated by Django 4.0.5 on 2022-06-28 00:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_comment_date_alter_replaycomment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 0, 0, 33, 597925, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='replaycomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 0, 0, 33, 598927, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 0, 0, 33, 596925, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='QuoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_quote_comment', models.TextField()),
                ('movie_id', models.CharField(max_length=20)),
                ('movie_title', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_nickname', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 6, 28, 0, 0, 33, 600040, tzinfo=utc))),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.comment')),
            ],
        ),
    ]
